### ISSUE TITLE
`dnx-watch` crashes for a certain class of errors in the target project.json file

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnx-watch#20]
`dnx-watch` is able to survive if the target project.json file is not well formed however it crashes when the validation of the contents fails. For instance adding `"resource": [ "c:/" ],` to the project.json file makes dnx-watch crash (or prevent from starting) with the following exception:

```
[DnxWatcher] info: File changed: C:\Users\xxxx\documents\visual studio 2015\Projects\HelloDNX\src\HelloDNX\project.json
C:\Users\xxxx\documents\visual studio 2015\Projects\HelloDNX\src\HelloDNX\project.json(16,15): Error: Microsoft.Dnx.Runtime.FileFormatException: The 'resource' property cannot be a rooted path. ---> System.InvalidOperationException: The 'resource' property cannot be a rooted path.
   at Microsoft.Dnx.Runtime.PatternsCollectionHelper.CreateCollection(String projectDirectory, String propertyName, IEnumerable`1 patternsStrings, Boolean literalPath)
   at Microsoft.Dnx.Runtime.PatternsCollectionHelper.GetPatternsCollection(JsonObject rawProject, String projectDirectory, String projectFilePath, String propertyName, IEnumerable`1 defaultPatterns, Boolean literalPath)
   --- End of inner exception stack trace ---
   at Microsoft.Dnx.Runtime.PatternsCollectionHelper.GetPatternsCollection(JsonObject rawProject, String projectDirectory, String projectFilePath, String propertyName, IEnumerable`1 defaultPatterns, Boolean literalPath)
   at Microsoft.Dnx.Runtime.PatternGroup.Build(JsonObject rawProject, String projectDirectory, String projectFilePath, String name, IEnumerable`1 fallbackIncluding, IEnumerable`1 additionalIncluding, IEnumerable`1 additionalExcluding, Boolean includePatternsOnly, ICollection`1 warnings)
   at Microsoft.Dnx.Runtime.ProjectFilesCollection.EnsureInitialized()
   at Microsoft.Dnx.Runtime.ProjectFilesCollection.get_SourceFiles()
   at Microsoft.Dnx.Watcher.Core.Project..ctor(Project runtimeProject)
   at Microsoft.Dnx.Watcher.Core.ProjectProvider.TryReadProject(String projectFile, IProject& project, String& errors)
   at Microsoft.Dnx.Watcher.Core.DnxWatcher.<WaitForValidProjectJsonAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Watcher.Core.DnxWatcher.<WatchAsync>d__6.MoveNext()
System.InvalidOperationException: The 'resource' property cannot be a rooted path.
   at Microsoft.Dnx.Runtime.PatternsCollectionHelper.CreateCollection(String projectDirectory, String propertyName, IEnumerable`1 patternsStrings, Boolean literalPath)
   at Microsoft.Dnx.Runtime.PatternsCollectionHelper.GetPatternsCollection(JsonObject rawProject, String projectDirectory, String projectFilePath, String propertyName, IEnumerable`1 defaultPatterns, Boolean literalPath)
```

**Comment by victorhurdugaci** [comment]
Fixed?
